### ISSUE TITLE
Add inverse properties we need

### ISSUE THREAD

**Issue by amoeba** [ec-geolink/d1lod#18]
This list at least includes prov:wasRevisionOf. I only add the wasRevisionOf property from the obsoletes field of the current dataset (which looks backward down the chain). Add the inverse property so that queries work.

**Comment by amoeba** [comment]
On second thought, prov doesn't establish anything like `prov:revises` or `prov:wasRevisedBy` so there's nothing to make the inverse of wasRevisionOf.

**Comment by mbjones** [comment]
@amoeba While PROV doesn't define inverses, it does recommend specific names for the inverse properties that should be used.  See PROV-O Appendix B: http://www.w3.org/TR/prov-o/#inverse-names for details and the list of inverse properties.

**Comment by amoeba** [comment]
Thanks, a bit slow this morning.
